data:
  alteration: all
  augmentation:
    photometric:
      enable: false
  dataset: coco
  export_folder: val
  gaussian_label:
    enable: false
    sigma: 1.0
  homography_adaptation:
    aggregation: sum
    enable: true
    filter_counts: 0
    homographies:
      params:
        allow_artifacts: true
        patch_ratio: 0.85
        perspective: true
        perspective_amplitude_x: 0.2
        perspective_amplitude_y: 0.2
        rotation: true
        scaling: true
        scaling_amplitude: 0.2
        translation: true
    num: 100
  name: patches_dataset
  preprocessing:
    resize:
    - 240
    - 320
eval_iter: -1
model:
  batch_size: 1
  detection_threshold: 0.015
  eval_batch_size: 1
  name: magic_point
  nms: 4
  top_k: 600
pretrained: logs/magicpoint_synth20/checkpoints/superPointNet_200000_checkpoint.pth.tar
